name: ml-rec
channels:
  - conda-forge
dependencies:
  - python=3.12

  # Core 
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - xgboost
  - joblib
  - pyarrow

  # Database / backend
  - sqlalchemy
  - pymysql
  - pydantic
  - fastapi
  - uvicorn

  # Notebook
  - ipykernel

  # Visualization
  - matplotlib
  - seaborn

  # Pip packages
  - pip
  - pip:
      # PyTorch stack
      - torch

      # PyTorch Geometric
      - torch_geometric

      # Recommender implicit matrix factorization
      - implicit

      # Chatbot / LangChain
      - python-dotenv
      - langchain
      - langsmith

      # RAG / Document Processing
      - langchain-community
      - langchain-text-splitters
      - langchain-pinecone